services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LetMiKnowDIDI2325!  # <-- СЛОЖНЫЙ ПАРОЛЬ
      POSTGRES_DB: alarm_sos
    # УДАЛИТЬ ports, чтобы закрыть базу от интернета!
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    restart: unless-stopped
    # УДАЛИТЬ ports для Redis, его тоже взламывают боты
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # API оставляем открытым, это нужно для юзеров
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # УКАЖИ НОВЫЙ ПАРОЛЬ ЗДЕСЬ ТОЖЕ:
      DATABASE_URL: postgresql://postgres:LetMiKnowDIDI2325!@postgres:5432/alarm_sos?connection_limit=5&pool_timeout=10
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_ACCESS_SECRET: super-secret-access-change-me
      JWT_REFRESH_SECRET: super-secret-refresh-change-me
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_EXPIRES: 7d
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata: